motoda sameAs
mto-2022-pn/lab1_1 pull request #11
Opened 2022-03-07 18:05 UTC by MateuszMatusiak

2022-03-07 18:10 UTC, radamuspl requested changes
Refaktoryzacja powinna być wykonana w krokach. A każdy krok być odrębnym commitem.

2022-03-07 18:10 UTC, radamuspl commented on src/main/java/pl/com/bottega/ecommerce/sales/domain/offer/Product.java
> +public class Product {
klasa powinna mieć swoje equals hashCode

2022-03-07 18:10 UTC, radamuspl commented on src/main/java/pl/com/bottega/ecommerce/sales/domain/offer/Money.java
> +    private BigDecimal amount;
klasa powinna mieć swoje equals hashCode

2022-03-07 18:10 UTC, radamuspl commented on src/main/java/pl/com/bottega/ecommerce/sales/domain/offer/OfferItem.java
> +    private final Money money;
nazwa pola `money` nic nie mówi o ty czym to pole jest.

2022-03-13 22:34 UTC, MateuszMatusiak commented
Poprawiona nazwa pola typu Money w OfferItem, metody equals w Product oraz Money. Nie mam początkowych commitów przez problem z Intelij.

2022-03-16 09:07 UTC, radamuspl approved these changes

2022-03-16 09:07 UTC, merged