Lab1_1
mto-2022-pn/lab1_1 pull request #9
Opened 2022-03-07 17:31 UTC by JakZaj

Nr indexu: 228897

2022-03-07 17:49 UTC, radamuspl requested changes

2022-03-07 17:49 UTC, radamuspl commented on src/main/java/pl/com/bottega/ecommerce/sales/domain/offer/Money.java
> +public class Money {
klasa powinna mieć swoje hashCode equals

2022-03-07 17:49 UTC, radamuspl commented on src/main/java/pl/com/bottega/ecommerce/sales/domain/offer/OfferItem.java
> +        this.product=new Product(product.getId(),product.getPrice(),product.getName(),productSnapshotDate,productType);
jest pan pewien, że to powinno być tak `this.product=new Product(product.getId()` ? Bo jak dla mnie to będzie NPE

2022-03-07 17:49 UTC, radamuspl commented on src/main/java/pl/com/bottega/ecommerce/sales/domain/offer/OfferItem.java
> +        result = prime * result + (product.getName() == null ? 0 : product.getName().hashCode());
Product powinien mieć swoje equals hashCode

2022-03-12 18:54 UTC, JakZaj commented
Korekta

2022-03-13 15:35 UTC, radamuspl approved these changes

2022-03-13 15:35 UTC, merged